server:
  port: 9098
sa-token:
  token-name: qrtoken
  token-prefix: Bearer
  token-style: simple-uuid
  is-print: false
  auto-renew: true
  is-concurrent: false
  is-read-cookie: true
  alone-redis:
    host: 127.0.0.1
    port: 6379
    database: 2
    password: 123456
    timeout: 500ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
  thymeleaf:
    cache: false