# Sa-Token-Quick-Login 配置
sa:
  # 登录账号
  name: admin
  # 登录密码
  pwd: admin
  # 是否自动随机生成账号密码 (此项为true时, name与pwd失效)
  auto: false
  # 是否开启全局认证(关闭后将不再强行拦截)
  auth: true
  # 登录页标题
  title: 登录
  # 是否显示底部版权信息
  copr: false
  include: /**
  exclude: /api/test/**
sa-token:
  is-print: false
server:
  port: 9999
  servlet:
    context-path: /management
spring:
  main:
    allow-circular-references: true
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduling-task-
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
async:
  executor:
    thread:
      core_pool_size: 5
      max_pool_size: 20
      queue_capacity: 100
      keep_alive_seconds: 100
      name:
        prefix: async-service-
